# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
# https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0

os: linux 

files:
  - source: /
    destination: /home/ec2-user/server
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1000
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 3600
      runas: root

  ApplicationStart:
    - location: scripts/start_app.sh     
      timeout: 300
      runas: root