version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
   
    commands:
        # install node 14
        # - curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -
        # - yum -y install nodejs npm
        # install npm
        - npm install
       
  build:
    commands:
        # run build script
        - npm run-script build
     
artifacts:
  # include all files required to run application
  # notably excluded is node_modules, as this will cause overwrite error on deploy
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*